main: main.c main.h bst.c bst.h rbtree.c rbtree.h
	gcc bst.c rbtree.c main.c -o main

dmain: main.c main.h bst.c bst.h rbtree.c rbtree.h
	gcc -g bst.c rbtree.c main.c -o dmain

reg: main.c main.h bst.c bst.h
	gcc bst.c main.c -o reg

